### ISSUE TITLE
read文档补充说明

### ISSUE THREAD

**Issue by IMGDemon** [Fenejifen/sql-work#1]
虚拟环境的配置可以参考这篇博客：https://blog.csdn.net/weixin_40964777/article/details/117700161?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522169859072016800215072519%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fblog.%2522%257D&request_id=169859072016800215072519&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_ecpm_v1~rank_v31_ecpm-1-117700161-null-null.nonecase&utm_term=%E6%80%8E%E4%B9%88%E5%9C%A8anaconda%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%B8%8B%E8%BD%BD%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%93&spm=1018.2226.3001.4450
然后用命令提示符复制mysql库可以参考以下两篇博客：
1.https://blog.csdn.net/xuiiao/article/details/129297574?ops_request_misc=&request_id=&biz_id=102&utm_term=%E6%80%8E%E4%B9%88%E4%B8%8B%E8%BD%BDmysql%E5%92%8Cmysqlworkbench&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~sobaiduweb~default-0-129297574.nonecase&spm=1018.2226.3001.4450
2.https://zhuanlan.zhihu.com/p/476698808
最后补充下在运行的时候需要先在sql.py文件里填写好你的用户名和密码否则代码运行不了
这个项目写的很不错也十分详细了，因为本人知识浅薄也在学习阶段，遇到的以上问题即相关解决方案在本issues上进行了补充，希望后面遇到相应问题的小白能够节约一点时间，更好地学习项目
最后再次谢谢作者精美的项目

**Comment by Fenejifen** [comment]
感谢你提出的issue。已经修改好啦=。=
